sudo: required
service:
  - docker

before_install:
  - docker build -t kunlesmart/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kunlesmart/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  origin: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-618549465378"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $access_key_id
  secret_access_key:
    secure: "$secret_access_key"